# Here you can specify default options for TinyMCE across all controllers

  theme: 'advanced'
  theme_advanced_resizing: true
  theme_advanced_resize_horizontal: false
  theme_advanced_toolbar_location: "top"
  theme_advanced_toolbar_align: "left"
  theme_advanced_statusbar_location: "bottom"

  theme_advanced_buttons1:
    - fullscreen
    - code
    - separator

    - bold
    - italic
    - underline
    - strikethrough
    - separator

    - justifyleft
    - justifycenter
    - justifyright
    - justifyfull
    - separator

    - sub
    - sup
    - separator

    - bullist
    - numlist
    - separator

    - outdent
    - indent
    - blockquote
    
  theme_advanced_buttons2:
    - link
    - unlink
    - separator

    - image
    - cleanup
    - separator

    - removeformat
    - formatselect
    - separator

    - forecolor
    - backcolor
    - separator

    - emotions

  theme_advanced_buttons3:
    - tablecontrols
    - table
    - row_props
    - cell_props
    - delete_col
    - delete_row
    - col_after
    - col_before
    - row_after
    - row_before
    - split_cells
    - merge_cells
    - separator

    - undo
    - redo

  theme_advanced_blockformats: "p,div,h1,h2,h3,h4,h5,h6,blockquote,dt,dd,code,samp"

  plugins:
    - table
    - fullscreen
    - emotions
    - inlinepopups
    - tabfocus

  width: "72%"

  tabfocus_elements: ":prev,:next"
