# Here you can specify default options for TinyMCE across all controllers

  theme: 'advanced'
  theme_advanced_resizing: true
  theme_advanced_resize_horizontal: false
  theme_advanced_toolbar_location: "top"
  theme_advanced_toolbar_align: "left"
  theme_advanced_statusbar_location: "bottom"

  theme_advanced_buttons1:
    - fullscreen
    - code
    - separator

    - bold
    - italic
    - underline
    - strikethrough
    - separator

    - justifyleft
    - justifycenter
    - justifyright
    - justifyfull
    - separator

    - bullist
    - numlist
    - separator

    - outdent
    - indent
    
  theme_advanced_buttons2:
    - formatselect
    - separator

    - link
    - unlink
    - separator

    - image
    - separator

    - forecolor
    - backcolor
    - separator

    - undo
    - redo

  theme_advanced_buttons3:
    - 

  theme_advanced_blockformats: "p,h1,h2,h3,h4,blockquote,code"

  plugins:
    - fullscreen
    - inlinepopups
    - tabfocus

  width: "72%"

  tabfocus_elements: ":prev,:next"
